######################################################################
# Automatically generated by qmake (2.01a) Do 27. Sep 21:16:48 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . graph
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h graph/edge.h graph/graph.h graph/node.h
SOURCES += main.cpp mainwindow.cpp graph/edge.cpp graph/graph.cpp graph/node.cpp
